[package]

name = "logistics"
version = "0.0.1"
authors = ["chrispryer"]
license = "MIT"
description = "Logistics Engineering Library"
repository = "https://github.com/andromia/logistics.git"
homepage = "https://github.com/andromia/logistics.git"
readme = "README.md"
keywords = [
    "logistics",
    "modeling",
    "supplychain",
    "supply",
    "chain",
    "operationsreseacrch",
    "operations",
    "research",
    "optimization",
    "logisticsengineering",
    "engineering"
]
categories = [
    "science", 
    "mathematics", 
    "business::operations research", 
    "business::supply chain"
]
exclude = [".vscode/", "Vagrantfile", "vm-bootstrap.sh"]

[package.metadata.docs.rs]
features = ["std"]

[dependencies]
